discourse/discourse-automation

- app/lib/discourse_automation/scripts/topic_required_words.rb
- app/lib/discourse_automation/triggers/topic.rb
- app/models/discourse_automation/trigger.rb
- assets/javascripts/discourse/templates/components/point-in-time-trigger.hbs
- assets/javascripts/discourse/templates/components/topic-trigger.hbs
- config/locales/client.en.yml
- config/locales/server.en.yml
- plugin.rb
- spec/jobs/discourse_automation_tracker_spec.rb
- spec/models/trigger_spec.rb
- spec/scripts/topic_required_words_spec.rb
- spec/triggers/topic_spec.rb
This commit also introduces the topic trigger which let's an automation mark a topic has "automation-able" (through a custom field), scripts and other utilities can then check if a topic is automation-able before applying any logic on it.
> FEATURE: implements topic_required_words script

- app/lib/discourse_automation/scripts/send_pms.rb
- app/lib/discourse_automation/triggers/user_promoted.rb
- config/locales/client.en.yml
- config/locales/server.en.yml
- plugin.rb
- spec/triggers/user_promoted_spec.rb
Added the new user_promoted trigger which has the following fields:
* restricted_group:       Will only run the script if the user being promoted
is in the specified group.
* trust_level_transition: Will only run the script if old to new trust
level matches what is specified here (e.g. 1
to 2), or for all trust level promotions.
We use the `:user_promoted event` from core for this new trigger. We do
not fire the automation trigger if the "promotion" is actually a
demotion e.g. 4 -> 1. We may want a separate event in core for this at
some point.
> FEATURE: Add user_promoted trigger and event hook

- app/core_ext/plugin_instance.rb
- app/lib/discourse_automation/scriptable.rb
- spec/integration/core_ext_spec.rb
This API allows plugins to add a defined triggerable as valid triggerable for a scriptable.
eg:
```
add_automation_triggerable(:foo) {}
add_triggerable_to_scriptable(:foo, :send_pms)
```
Note this commit also adds a missing `add_automation_triggerable` API
> DEV: adds plugin triggerable API

- app/queries/stalled_topic_finder.rb
- spec/jobs/stalled_topic_tracker_spec.rb
- spec/queries/stalled_topic_finder_spec.rb
- spec/triggers/recurring_spec.rb
Before this change a topic with only the OP could be considered stalled even if it was recent as the query would only consider post_number > 1
> FIX: a topic can be stalled even if it only has OP

- app/lib/discourse_automation/scripts/auto_responder.rb
- app/lib/discourse_automation/triggers/post_created_edited.rb
- app/models/discourse_automation/field.rb
- assets/javascripts/discourse/components/automation-field.js.es6
- assets/javascripts/discourse/components/fields/da-base-field.js.es6
- assets/javascripts/discourse/components/fields/da-key-value-field.js.es6
- assets/javascripts/discourse/components/fields/da-trust-levels-field.js.es6
- assets/javascripts/discourse/templates/admin-plugins-discourse-automation-edit.hbs
- assets/javascripts/discourse/templates/components/automation-field.hbs
- assets/javascripts/discourse/templates/components/fields/da-key-value-field.hbs
- assets/javascripts/discourse/templates/components/fields/da-trust-levels-field.hbs
- config/locales/client.en.yml
- config/locales/server.en.yml
- plugin.rb
- spec/scripts/auto_responder_spec.rb
- spec/triggers/post_created_edited_spec.rb
The auto responder script allows to define a list of keys/values which will be used to react to a post content. If a post contains KEY, then a reply using VALUE will be made to the post.
Note that this commit also introduces the ability for the post_created_edited trigger to limit its action to specific trust_levels creators.
> FEATURE: adds auto_responder script

- app/lib/discourse_automation/scripts/auto_responder.rb
- spec/scripts/auto_responder_spec.rb
In the future I would like to have a custom error panel in automation, but for now it's fine to just do nothing in this case.
> FIX: an empty word/answer list doesn’t generate an exception

- app/lib/discourse_automation/scripts/auto_responder.rb
- spec/scripts/auto_responder_spec.rb
Previously this would print the full regex instead of the captured match.
> FIX: correctly uses matched value in raw for placeholder

- app/lib/discourse_automation/scripts/zapier_webhook.rb
Technically this shouldn't be possible while using the app, but this can be hit in tests for example.
> FIX: ensures we don't crash if url is given

- app/lib/discourse_automation/scripts/auto_responder.rb
- spec/jobs/stalled_topic_tracker_spec.rb
- spec/requests/discourse_automation_automations_spec.rb
- spec/triggers/post_created_edited_spec.rb
Our Rubocop rules ban `JSON.load` because it's unsafe when used with untrusted data so we need to switch to `JSON.parse`. Minor refactoring is needed because `JSON.load` doesn't raise when it's given an empty string or nil, but `JSON.parse` does.
> DEV: Use JSON.parse instead of JSON.load

- plugin.rb
- spec/scripts/topic_required_words_spec.rb
This was also causing an issue in tests where a post could be created without a topic.
> FIX: prevents automation to run when not needed in few cases

- app/lib/discourse_automation/scriptable.rb
- app/serializers/discourse_automation/automation_serializer.rb
- spec/lib/scriptable_spec.rb
In any field allowing placeholders like PM body:
```
This is the last likes report:
%%REPORT=likes%%
```
Will be replaced by:
```
This is the last likes report:
|Day|Count|
|-|-|
|2022-02-25|2|
```
For now it doesn’t support specific args and will just use defaults.
> FEATURE: allows to insert reports using placeholders syntax

- app/controllers/admin/discourse_automation/admin_discourse_automation_triggerables_controller.rb
This would cause on specific circumstance `automation.scriptable.triggerables` to be altered and return an array of hash for next run instead of an array of strings.
> FIX: ensures we don't mutate automation object

- plugin.rb
The same exact route is declared a few lines (line 147-149) earlier so I think this was added erroneously and can be removed.
> DEV: Remove duplicate route

- app/lib/discourse_automation/scriptable.rb
- app/lib/discourse_automation/scripts/send_pms.rb
- app/lib/discourse_automation/scripts/zapier_webhook.rb
- app/lib/discourse_automation/triggers/user_badge_granted.rb
- app/services/discourse_automation/user_badge_granted_handler.rb
- assets/javascripts/discourse/components/fields/da-choices-field.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- plugin.rb
- spec/services/user_badge_granted_spec.rb
- spec/triggers/user_badge_granted_spec.rb
This trigger needs a `badge` as required field and accepts an optional `only_on_first_grant` field. ATM it’s usable for: `send_pms` and `zapier_webhook` scripts.
> FEATURE: adds a user_granted_badge trigger

- app/lib/discourse_automation/triggers/recurring.rb
- spec/triggers/recurring_spec.rb
The `INTERVAL` param is working differently in `RRule` when we use it with `BYDAY=MO,TU,WE,TH,FR` param to find out weekdays. So we removed it and using a different calculation to find the weekday.
> FIX: remove `INTERVAL` param from `RRule` in weekday calculation.

- assets/javascripts/discourse/helpers/format-enabled-automation.js
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions
> DEV: Remove 'htmlSafe' string prototype extensions

- app/services/discourse_automation/user_badge_granted_handler.rb
- spec/services/user_badge_granted_spec.rb
grant_count is a global counter for grants of this badge across all users, not the count for a specific user. This commit now correctly checks if the badge has been awarded more than once.
> FIX: automation was checking grant_count incorrectly

- app/services/discourse_automation/user_badge_granted_handler.rb
- spec/services/user_badge_granted_spec.rb
Tests were erroneous as multiple grant was silently preventing multiple badges to be created
> FIX: triggers on first badge

- app/lib/discourse_automation/scripts/add_user_to_group_through_custom_field.rb
- config/locales/client.en.yml
- config/locales/server.en.yml
- plugin.rb
- spec/scripts/add_user_to_group_through_custom_field_spec.rb
The new `add_user_to_group_through_custom_field` script accepts a Recurring trigger, and takes the name of a User Custom Field containing a group name.
On each run, it ensures that each user belongs to the group name given by their UCF.
In other words, it designates a certain User Custom Field to act as a "pointer" to a group that the user should belong to, and adds users to that group as needed.
> Add add_user_to_group_through_custom_field script

- app/lib/discourse_automation/scripts/add_user_to_group_through_custom_field.rb
- spec/scripts/add_user_to_group_through_custom_field_spec.rb
Match on group.full_name rather than group.name, so that the UCF can use user friendly values (ie. `United States`) rather than valid group names (ie. `UnitedStates`).
> add_user_to_group_through_custom_field_spec: use group.full_name

- app/lib/discourse_automation/triggers/after_post_cook.rb
- config/locales/client.en.yml
- plugin.rb
- spec/discourse_automation_helper.rb
- spec/jobs/stalled_topic_tracker_spec.rb
- spec/models/automation_spec.rb
- spec/requests/discourse_automation_automations_spec.rb
- spec/services/user_badge_granted_spec.rb
- spec/triggers/after_post_cook_spec.rb
- spec/triggers/pm_created_spec.rb
- spec/triggers/post_created_edited_spec.rb
- spec/triggers/stalled_wiki_spec.rb
- spec/triggers/user_added_to_group_spec.rb
- spec/triggers/user_badge_granted_spec.rb
- spec/triggers/user_promoted_spec.rb
Previously we could only filter after post cooked triggers by category,
this enables tag filtering as well. (applicable to checked / edited by)
Also, contains a major refactor of testing which used to depend on stdout
capturing and json parsing which can be fragile if anything leaks onto stdout
New framework `capture_contexts` is more targetted and easier to consume
> FEATURE: allow tag filter on after post cooked

- spec/discourse_automation_helper.rb
It wasn't safe to emit events in specs outside `capture_contexts` blocks
```
1) UserPromoted does not run if the user is being demoted
Failure/Error: block.call(*args) if enabled?
NoMethodError:
undefined method `<<' for nil:NilClass
```
> DEV: Fix spec failure

- assets/javascripts/discourse/controllers/admin-plugins-discourse-automation-index.js
This isn't a security bug, because only admins can create automations and we have to trust admins, because they can change themes, which are shown site-wide and can contain unrestricted JS.
It's still good to fix though.
> FIX: Escape HTML tags before rendering delete button

- spec/triggers/pm_created_spec.rb
See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.
> DEV: Fix specs for personal_message_enabled_groups setting

- app/controllers/admin/discourse_automation/admin_discourse_automation_automations_controller.rb
- assets/javascripts/discourse/templates/admin-plugins-discourse-automation-edit.hbs
- assets/stylesheets/common/discourse-automation.scss
- spec/requests/admin_discourse_automation_automations_spec.rb
Under specific circumstances, automation could be saved as enabled without a trigger, leading to the automation staying enabled after adding an uncompleted trigger.
This could eventually be moved into some automation validation, but that can be pretty tricky to do given the chicken-egg situation of script needing trigger, trigger requiring automation, ... and other added complexity like the validity of relationships (fields of the scripts/triggers, enabled or not...).
The enabled checkbox has been moved to the bottom and, more importantly, is only showing if a trigger is set. We could need a different pattern for this as in the past, having this field at the bottom led to people not seeing it, but this is too much complexity for now.
> FIX: prevents saving an enabled automation with no trigger

- app/lib/discourse_automation/triggers/recurring.rb
- assets/javascripts/discourse/templates/admin-plugins-discourse-automation-edit.hbs
No logic changed, just re-ordering the `next_trigger_date` switch to go from the smallest frequency to the highest (and match the order of the `RECURRENCE_CHOICES` array.
The `admin-plugins-discourse-automation-edit.hbs` was also linted.
> DEV: re-order trigger date code to match recurrence choices

- app/lib/discourse_automation/scripts/post.rb
- spec/scripts/post_spec.rb
If the topic was deleted and a post script ran, we would
get this error:
> Job exception: Something has gone wrong. Perhaps this topic was closed or deleted while you were looking at it?
We can't create a post on a deleted topic, so just do nothing
if that happens.
> FIX: Do not error on deleted topic in post script

- db/migrate/20230412120414_add_prefers_encrypt_field_to_pending_pms.rb
Since there are already rows in `discourse_automation_pending_pms`, we
cannot add a column with `null: false`. Instead we need to first add the
column, fill it up with values and then change the column default.
> FIX: Update migration to prevent `PG::NotNullViolation` error

- app/lib/discourse_automation/scripts/send_pms.rb
- spec/scripts/send_pms_spec.rb
This reverts commit bcd604a25bd2a99e4babe77e6c712b59fd49550b.
> FIX: PG::NotNullViolation when prefers_encrypt is not set

- config/locales/server.en.yml
- lib/discourse_automation/scripts/add_user_to_group_through_custom_field.rb
- lib/discourse_automation/triggers/user_first_logged_in.rb
- plugin.rb
- spec/scripts/add_user_to_group_through_custom_field_spec.rb
- spec/triggers/user_first_logged_in_spec.rb
Adds a new `user_first_logged_in` trigger and makes it available to `add_user_to_group_through_custom_field` script.
It replaces using `user_added_to_group` which was happening too late for this use case.
Example UI of an automation using it:
> FEATURE: adds user_first_logged_in trigger

- lib/discourse_automation/event_handlers.rb
- spec/triggers/after_post_cook_spec.rb
- spec/triggers/post_created_edited_spec.rb
Previously, the `post_created_edited` and `after_post_cook` triggers did not support subcategories. 
This also ensure that the triggers work the same way for parent categories, i.e. if a parent category is selected, the hook will fire posts assigned to the parent AND on posts assigned to its direct subcategories.
> FEATURE: Support subcategories in `post_created_edited` and `after_post_cook`

- app/models/discourse_automation/field.rb
- spec/models/field_spec.rb
Fixes an issue where emptying a choices component would fail validation (and skip saving the edit):
> FIX: Allow choices components to be reset

- config/locales/server.en.yml
- lib/discourse_automation/scripts/user_global_notice.rb
- spec/scripts/user_global_notice_spec.rb
The user global notice script only supported the stalled topic triggerable.
This PR adds the first accepted answer triggerable from `discourse-solved` to the user global notice script if `discourse-solved` is installed.
I've separated the stalled topic triggerable tests to its own context to help clarity.
> FEATURE: add first accepted answer triggerable to user global notice script

- app/jobs/scheduled/discourse_automation_tracker.rb
This file shouldn't be loaded twice but it is 🥲 I debugged it for a while but could figure it out. Let's just `||=` it.
> DEV: Avoid constant redefinition warning

- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/discourse_automation/scripts/user_group_membership_through_badge.rb
- plugin.rb
- spec/scripts/user_group_membership_through_badge_spec.rb
This change adds a new script, `user_group_membership_through_badge` which provides the option to automate user group memberships through badges.
Given a badge name and a group, it adds users with the specified badged to the the given group either on login or on a recurring schedule.
It also has an optional flag to synchronize these two in "strict mode". It does this by ensuring only users with the specified badge belong to the given group.
> FEATURE: Add script to modify user group memberships through badges

- config/locales/client.en.yml
- lib/discourse_automation/scripts/user_group_membership_through_badge.rb
- spec/scripts/user_group_membership_through_badge_spec.rb
Introduce the option to keep user title and flair updated for each group membership change triggered by `user_group_membership_through_badge` automation.
See  https://github.com/discourse/discourse-automation/pull/206
> FEATURE: Option to force title and flair updates for badge-group syncs

- lib/discourse_automation/event_handlers.rb
- plugin.rb
Added back in 3350bb9288027077d1c46d27feaa1185a368bac9, this
moving this into a method for EventHandlers for consistency, not
just inlined into plugin.rb
> DEV: Refactor stalled topic into EventHandlers

- assets/javascripts/discourse/components/fields/da-key-value-field.js
- assets/javascripts/discourse/templates/components/fields/da-key-value-field.hbs
- assets/stylesheets/common/discourse-automation.scss
- config/locales/client.en.yml
- lib/discourse_automation/event_handlers.rb
- lib/discourse_automation/scripts/auto_responder.rb
- lib/discourse_automation/triggers/pm_created.rb
- lib/discourse_automation/triggers/post_created_edited.rb
- spec/scripts/auto_responder_spec.rb
- spec/triggers/pm_created_spec.rb
- spec/triggers/post_created_edited_spec.rb
This commit introduces some additional options to make the
pm_created and post_created_edited triggers more useable as
auto-responders inside group inboxes.
* restricted_group - Will only call the trigger if the topic is a PM
sent to the specified group.
* ignore_automated - If the post/topic is being created from an incoming
email, and it is from a noreply address or otherwise automated, then it
will not be considered valid for the autoresponder to reply to.
* ignore_group_members - When combined with restricted_group, the
autoresponder will not fire the trigger if the post/topic is being
created by a member of the group.
This commit also does some minor refactors and makes some UI
and copy improvements.
Needs https://github.com/discourse/discourse/pull/23364
> FEATURE: Additional options for pm_created and post_created_edited triggers

- lib/discourse_automation/event_handlers.rb
- spec/triggers/post_created_edited_spec.rb
When a restricted_group was specified for a post_created_edited
trigger, we were only checking for the group validity if the topic
was a PM. However, we weren't handling the opposite case -- if the
topic is a public topic and there is a restricted_group, then we
want to skip the trigger, since the group param is only meant to work
with group inboxes.
> FIX: Post created event issue when group specified

- assets/javascripts/discourse/components/automation-field.js
The locale option is not necessary when calling I18n.lookup,
and furthermore this was making the description for fields not
show if using an untranslated locale, rather than just falling
back to en-US.
> FIX: I18n lookup locale

- assets/javascripts/discourse/components/fields/da-group-field.js
- lib/discourse_automation/scripts/user_group_membership_through_badge.rb
This is now only used in `USER_GROUP_MEMBERSHIP_THROUGH_BADGE` script and `false` by default.
> DEV: allows to ignore automatic groups from group component

- app/serializers/discourse_automation/automation_serializer.rb
- lib/discourse_automation/scriptable.rb
- spec/lib/scriptable_spec.rb
Only explicit placeholders defined with the `placeholder` syntax will be shown under fields. `%%SITE_TITLE%%` and `%%REPORT=report_name%%` will keep working but the buttons to add them won't be displayed by default under each field.
> UX: do not show implicit placeholders

- assets/javascripts/discourse/helpers/format-delay.js
- assets/javascripts/discourse/helpers/format-enabled-automation.js
- Deletes unused format-delay helper
- Updates format-enabled-automation helper to be a default export
> DEV: Resolve registerUnbound deprecation

- config/locales/client.en.yml
- db/migrate/20231017175757_change_user_group_membership_through_badge_script_badge_name_field_to_badge.rb
- lib/discourse_automation/scripts/user_group_membership_through_badge.rb
- spec/scripts/user_group_membership_through_badge_spec.rb
- spec/system/smoke_test_spec.rb
This changes the `badge_name` script field to `badge` and component type from free form text to dropdown
> DEV: Change user_group_membership_through_badge's badge_name field

- app/controllers/discourse_automation/automations_controller.rb
- app/models/discourse_automation/automation.rb
- spec/requests/discourse_automation_automations_spec.rb
Currently, long running automations lead to timeouts.
This change moves automation trigger to the background instead of running it in the web process.
> FIX: Always run automations in background when triggered via API

- assets/javascripts/discourse/components/fields/da-boolean-field.gjs
- assets/javascripts/discourse/components/fields/da-categories-field.gjs
- assets/javascripts/discourse/components/fields/da-category-field.gjs
- assets/javascripts/discourse/components/fields/da-category-notification-level-field.gjs
- assets/javascripts/discourse/components/fields/da-choices-field.gjs
- assets/javascripts/discourse/components/fields/da-custom-field.gjs
- assets/javascripts/discourse/components/fields/da-date-time-field.gjs
- assets/javascripts/discourse/components/fields/da-email-group-user-field.gjs
- assets/javascripts/discourse/components/fields/da-group-field.gjs
- assets/javascripts/discourse/components/fields/da-key-value-field.gjs
- assets/javascripts/discourse/components/fields/da-message-field.gjs
- assets/javascripts/discourse/components/fields/da-period-field.gjs
- assets/javascripts/discourse/components/fields/da-pms-field.gjs
- assets/javascripts/discourse/components/fields/da-post-field.gjs
- assets/javascripts/discourse/components/fields/da-tags-field.gjs
- assets/javascripts/discourse/components/fields/da-text-field.gjs
- assets/javascripts/discourse/components/fields/da-text-list-field.gjs
- assets/javascripts/discourse/components/fields/da-trust-levels-field.gjs
- assets/javascripts/discourse/components/fields/da-user-field.gjs
- assets/javascripts/discourse/components/placeholders-list.gjs
- assets/javascripts/discourse/controllers/admin-plugins-discourse-automation-new.js
It was complaining a lot here https://github.com/discourse/discourse-automation/actions/runs/7112464501/job/19362457179?pr=235
```
/home/runner/work/discourse-automation/discourse-automation/assets/javascripts/discourse/components/fields/da-boolean-field.gjs
Error:   1:1  error  Run autofix to sort these imports!  simple-import-sort/imports
/home/runner/work/discourse-automation/discourse-automation/assets/javascripts/discourse/components/fields/da-categories-field.gjs
Error:   1:1  error  Run autofix to sort these imports!  simple-import-sort/imports
/home/runner/work/discourse-automation/discourse-automation/assets/javascripts/discourse/components/fields/da-category-field.gjs
Error:   1:1  error  Run autofix to sort these imports!  simple-import-sort/imports …
```
> DEV: eslint fixes to imports and property order

- lib/discourse_automation/scriptable.rb
- spec/jobs/discourse_automation_tracker_spec.rb
- spec/lib/scriptable_spec.rb
In another plugin that is using the Send PM feature (discourse-data-explorer), when a PM is sent that violates `SiteSetting.max_post_length`, there is no indication that the PM did not send.
Raising an error here can help surface that.
> UX: Throw an error when PM creation fails

- spec/queries/stalled_topic_finder_spec.rb
- spec/triggers/post_created_edited_spec.rb
In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.
> DEV: Replace deprecated min_trust_to_create_post

- app/controllers/discourse_automation/admin_scriptables_controller.rb
- app/serializers/discourse_automation/template_serializer.rb
- assets/javascripts/discourse/admin/models/discourse-automation-field.js
- assets/stylesheets/common/discourse-automation.scss
- lib/discourse_automation/scriptable.rb
- spec/system/smoke_test_spec.rb
In certain cases when creating an automation we may want to pre-populate
fields
This allows us to use `default_value: ...` to denote a default value for an
automation.
Also
- Fixes CSS on recurring automations, message was not aligned correctly
- Sort scriptables so we don't return them in random order
> FEATURE: support default values for scriptables

- lib/discourse_automation/scriptable.rb
- spec/lib/scriptable_spec.rb
This fix checks for the PM's target_users existence, removes non-existent target users, then sends the PM depending on whether there are any valid target users. Warnings are also added to the rails logs.
This also allows the DiscourseAutomation::PendingPm to be successfully cleared.
Our automation job has an error that was surfaced:
```
Job exception: One of the users you are sending this message to could not be found.
```
This may happen if a user account is deleted after getting added to a group, and the automation sends the PM X minutes after the trigger. e.g. the screenshot below.
> FIX: Skip sending PMs to non-existent users

- spec/scripts/auto_tag_topic_spec.rb
We've been moving TL based access to group based access in core. This requires auto-groups to be created in relevant tests for them to keep passing.
> DEV: Handle auto-group refresh to fix tests

- lib/discourse_automation/triggers/recurring.rb
- spec/triggers/recurring_spec.rb
Prior to this fix, we would start to look for next daily event from the end of the current day. This could be problematic when you want to start scheduling an event later today.
> FIX: computes next daily recurring from now

- app/models/discourse_automation/field.rb
- assets/javascripts/discourse/components/automation-field.gjs
- assets/javascripts/discourse/components/fields/da-custom-fields.gjs
- assets/javascripts/discourse/components/fields/da-user-profile-field.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/discourse_automation/event_handlers.rb
- lib/discourse_automation/scripts/post.rb
- lib/discourse_automation/triggers/user_updated.rb
- plugin.rb
- spec/scripts/post_spec.rb
- spec/triggers/user_updated_spec.rb
**Context**
Customer wants to be able to create posts when a user joins their community.
**Problem**
The current implementation of the Automation plugin doesn't support the creation of Posts after user creation or update.
**Solution**
Implement a workflow to allow the Automation plugin `Post` script to work with the `user_updated` event by creating a corresponding trigger and event handler.  Implement logic to make sure the script doesn't run if the user hasn't filled in the required information and/or, if there should only be a post of this type, there is no duplication of this post.
> FEATURE: Automated Post creation on user updated

- app/models/discourse_automation/automation.rb
- assets/javascripts/discourse/components/fields/da-period-field.gjs
- config/locales/server.en.yml
- lib/discourse_automation/scripts/post.rb
- lib/discourse_automation/triggerable.rb
- lib/discourse_automation/triggers/user_updated.rb
- spec/triggers/user_updated_spec.rb
- Implements a concept of "validation" for automation, so you can perform custom validations
- Stop requiring both custom_fields and user_fields, allow only 1
- Fix issue with Periodical Selector not working at all in a development environment
> FEATURE: allow either custom_fields or user_fields in trigger

- app/serializers/discourse_automation/automation_serializer.rb
- lib/discourse_automation/scripts/post.rb
- spec/serializers/automation_serializer_spec.rb
Custom fields can be free form, eg: "Foo bar". We want to be sure this is rendered in the template as "foo_bar" as this is also how we will fill the placeholders map in scripts.
> FIX: correctly format placeholders

- lib/discourse_automation/scriptable.rb
- spec/lib/scriptable_spec.rb
Our PostCreator in core allows us to send PMs to groups, however we lack the ability to do this via Discourse Automation.
This change allows automation scripts to pass the `target_group_names` as an array.
> FEATURE: add groups to send pm in scriptable utils

- app/jobs/regular/discourse_automation_trigger.rb
In case of error while evaluating a script running in the background, the job will retry after 5/15/120 minutes.
Note this retry syntax is quite convulted at the moment and should be improved in the future.
> DEV: retry 3 times background trigger

- lib/discourse_automation/scriptable.rb
- spec/lib/scriptable_spec.rb
Why this change?
In core the TopicCreator accepts a comma separated string for `target_emails`. Our automation script within DataExplorer allows email addresses to be specified as PM recipients, however the scriptable utils within Discourse Automation previously only accepted usernames and therefore emails weren't being sent as they didn't have an account attached and got filtered.
This change ensures emails are handled and validated in the correct way, as they passed in the correct format.
> FEATURE: add emails to send pm in scriptable utils

- lib/discourse_automation/scripts/post.rb
- spec/scripts/post_spec.rb
Currently, the post script will continue adding posts to the configured topic even when it's closed/archived.
This change updates the script to skip closed/archived topics.
> FIX: Skip closed/archived topics during post script runs

- plugin.rb
Adds this message to inform admins to remove this plugin, since it is now a core plugin.
> DEV: Inform self-hosted admins to remove discourse-automation
